name: CI Workflow

on:
  push:
    branches:
    - program8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI
        run: echo "Build and Test Successful"